apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-appium
  labels:
    app: selenium-node-appium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-appium
  template:
    metadata:
      labels:
        app: selenium-node-appium
    spec:
      containers:
      - name: selenium-node-appium
        image: butomo1989/docker-android-x86-8.0
        ports:
          - containerPort: 5900
        env:
          - name: HUB_HOST
            value: "selenium-hub"
          - name: HUB_PORT
            value: "4444"
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2"